'use client';

import { useState, useEffect } from 'react';
import {
  ShieldCheck,
  AlertTriangle,
  CheckCircle2,
  Info,
  RefreshCcw,
  Search,
  FileText,
  ScanSearch,
  ChevronRight,
  Target,
  FolderPlus
} from 'lucide-react';
import SaveToProjectModal from '@/components/shared/SaveToProjectModal';

interface ValidationResult {
  score: number;
  hallucinations: { text: string; reason: string; severity: 'high' | 'medium' | 'low' }[];
  suggestions: string[];
  isSafe: boolean;
  formatting: { label: string; passed: boolean }[];
}

const t = {
  vi: {
    title: 'Output Validator',
    desc: 'Kiểm định kết quả từ AI, phát hiện ảo giác (hallucination) và đánh giá độ chính xác, an toàn.',
    reset: 'Reset',
    inputLabel: 'Văn bản cần kiểm định (AI Output)',
    inputPlaceholder: 'Dán câu trả lời của AI vào đây để kiểm tra tính chính xác...',
    chars: 'ký tự',
    contextLabel: 'Ngữ cảnh / Yêu cầu gốc (Tùy chọn)',
    contextPlaceholder: 'Nhập prompt ban đầu hoặc tài liệu tham khảo để đối chiếu tốt hơn...',
    hint: 'Nhập tối thiểu 20 ký tự để bắt đầu kiểm định',
    analyzing: 'Đang phân tích...',
    validateBtn: 'Kiểm định ngay',
    criteriaTitle: 'Tiêu chí kiểm định',
    c1: 'Độ tin cậy (Hallucination)',
    c1d: 'Phát hiện các thông tin bịa đặt, sai sự thật do AI tự sinh ra.',
    c2: 'Đánh giá tính logic',
    c2d: 'Kiểm tra xem câu trả lời có mâu thuẫn nội tại hay không.',
    c3: 'An toàn & Đạo đức',
    c3d: 'Lọc từ ngữ độc hại, thiên kiến hoặc vi phạm tiêu chuẩn cộng đồng.',
    score: 'Confidence Score',
    scoreDesc: 'Dựa trên đối chiếu đa chiều và fact-checking.',
    checkTitle: 'Kiểm tra định dạng & ngữ cảnh',
    check1: 'Kiểm tra {n} phát ngôn (Claims)',
    check2: 'Độ tin cậy tổng thể > 50%',
    check3: 'Không có phát ngôn bị bác bỏ',
    suggestTitle: 'Gợi ý cải thiện',
    suggestMsg1: 'Kiểm tra lại các nguồn thông tin nếu có phát ngôn chưa xác thực.',
    dangerTitle: 'Phát hiện nguy cơ ảo giác (Hallucinations)',
    reasonLabel: 'Lý do: ',
    errConn: 'Không thể kết nối đến server backend.',
    errGen: 'Có lỗi xảy ra khi kiểm định.'
  },
  en: {
    title: 'Output Validator',
    desc: 'Validate AI output, detect hallucinations, and evaluate accuracy and safety.',
    reset: 'Reset',
    inputLabel: 'Text to Validate (AI Output)',
    inputPlaceholder: 'Paste the AI response here to verify its accuracy...',
    chars: 'chars',
    contextLabel: 'Context / Original Prompt (Optional)',
    contextPlaceholder: 'Enter the initial prompt or reference material for better comparison...',
    hint: 'Enter at least 20 characters to start validation',
    analyzing: 'Analyzing...',
    validateBtn: 'Validate Now',
    criteriaTitle: 'Validation Criteria',
    c1: 'Reliability (Hallucination)',
    c1d: 'Detect fabricated or false information generated by AI.',
    c2: 'Logic Assessment',
    c2d: 'Check if the answer has internal contradictions.',
    c3: 'Safety & Ethics',
    c3d: 'Filter toxic language, bias, or community standards violations.',
    score: 'Confidence Score',
    scoreDesc: 'Based on multi-dimensional cross-referencing and fact-checking.',
    checkTitle: 'Format & Context Checks',
    check1: 'Checked {n} claims',
    check2: 'Overall reliability > 50%',
    check3: 'No disputed claims',
    suggestTitle: 'Suggestions for Improvement',
    suggestMsg1: 'Double check information sources for unverified claims.',
    dangerTitle: 'Hallucination Risks Detected',
    reasonLabel: 'Reason: ',
    errConn: 'Cannot connect to backend server.',
    errGen: 'An error occurred during validation.'
  }
};

export default function ValidatorPage() {
  const [lang, setLang] = useState('vi');

  useEffect(() => {
    setLang(localStorage.getItem('app_lang') || 'vi');
    const handleLangChange = () => setLang(localStorage.getItem('app_lang') || 'vi');
    window.addEventListener('storage', handleLangChange);
    window.addEventListener('app_lang_changed', handleLangChange);
    return () => {
      window.removeEventListener('storage', handleLangChange);
      window.removeEventListener('app_lang_changed', handleLangChange);
    };
  }, []);

  const text = t[lang as 'en' | 'vi'] || t.vi;

  const [output, setOutput] = useState('');
  const [context, setContext] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<ValidationResult | null>(null);
  const [showSaveModal, setShowSaveModal] = useState(false);

  const charCount = output.length;
  const canValidate = output.trim().length >= 20 && !loading;

  const handleValidate = async () => {
    if (!canValidate) return;
    setLoading(true);
    setResult(null);

    try {
      const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000'}/api/validator`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          text: output,
          geminiKey: typeof window !== 'undefined' ? localStorage.getItem('geminiKey') || undefined : undefined
        }),
      });

      const json = await res.json();
      
      if (res.ok && json.success !== false) {
        // Map backend ValidatorResult to frontend ValidationResult
        const formattedResult: ValidationResult = {
          score: json.overallScore || 0,
          isSafe: json.disputedCount === 0,
          hallucinations: (json.claims || [])
            .filter((c: any) => c.status === 'disputed' || c.status === 'unverified')
            .map((c: any) => ({
              text: c.claim,
              reason: c.explanation,
              severity: c.status === 'disputed' ? 'high' : 'medium'
            })),
          suggestions: [
            json.summary || '',
            text.suggestMsg1,
          ],
          formatting: [
            { label: text.check1.replace('{n}', (json.totalClaims || 0).toString()), passed: (json.totalClaims || 0) > 0 },
            { label: text.check2, passed: (json.overallScore || 0) > 50 },
            { label: text.check3, passed: json.disputedCount === 0 },
          ]
        };
        setResult(formattedResult);

        // Log lịch sử hoạt động
        const token = localStorage.getItem('token');
        if (token) {
          fetch(`${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000'}/api/profile/history`, {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              'Authorization': `Bearer ${token}`
            },
            body: JSON.stringify({
              action: 'Validate AI Output',
              tool: 'Output Validator',
              detail: `Text: ${output.substring(0, 60)}${output.length > 60 ? '...' : ''}`,
              model: 'System',
              prompt: output,
              result: json.summary || 'Validation Completed'
            })
          }).catch(err => console.error('Lỗi khi lưu lịch sử:', err));
        }
      } else {
        console.error('Validation error:', json.message);
        alert(json.message || text.errGen);
      }
    } catch (error) {
      console.error('Failed to validate output:', error);
      alert(text.errConn);
    } finally {
      setLoading(false);
    }
  };

  const handleReset = () => {
    setOutput('');
    setContext('');
    setResult(null);
  };

  return (
    <div className="max-w-6xl mx-auto space-y-6 pb-12">
      {/* ── Header ─────────────────────────────────────────────────────────── */}
      <div className="flex items-start justify-between">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <div className="w-8 h-8 rounded-xl bg-gradient-to-br from-emerald-500 to-teal-700 flex items-center justify-center shadow-md shadow-emerald-200">
              <ShieldCheck className="w-4 h-4 text-white" />
            </div>
            <h1 className="text-2xl font-black text-slate-900">{text.title}</h1>
          </div>
          <p className="text-sm text-slate-500">
            {text.desc}
          </p>
        </div>
        {result && (
          <button
            onClick={handleReset}
            className="flex items-center gap-1.5 px-3 py-2 rounded-xl border border-slate-200 text-sm text-slate-600 hover:bg-slate-50 transition"
          >
            <RefreshCcw className="w-3.5 h-3.5" /> {text.reset}
          </button>
        )}
      </div>

      {/* ── Input Area ─────────────────────────────────────────────────────── */}
      <div className="grid grid-cols-1 lg:grid-cols-[1fr_350px] gap-6">
        
        <div className="space-y-4">
          <div className="bg-white rounded-2xl border border-slate-100 shadow-sm overflow-hidden">
            <div className="flex items-center justify-between px-5 py-3 border-b border-slate-100 bg-slate-50/50">
              <span className="text-sm font-semibold text-slate-700 flex items-center gap-2">
                <FileText className="w-4 h-4 text-slate-400" />
                {text.inputLabel}
              </span>
              <span className={`text-xs font-medium ${charCount > 5000 ? 'text-amber-500' : 'text-slate-400'}`}>
                {charCount}/5000 {text.chars}
              </span>
            </div>

            <textarea
              value={output}
              onChange={(e) => setOutput(e.target.value)}
              placeholder={text.inputPlaceholder}
              maxLength={5000}
              rows={8}
              className="w-full px-5 py-4 text-sm text-slate-800 placeholder:text-slate-400 focus:outline-none resize-none leading-relaxed"
            />
          </div>

          <div className="bg-white rounded-2xl border border-slate-100 shadow-sm overflow-hidden">
            <div className="flex items-center px-5 py-3 border-b border-slate-100 bg-slate-50/50">
              <span className="text-sm font-semibold text-slate-700 flex items-center gap-2">
                <Target className="w-4 h-4 text-slate-400" />
                {text.contextLabel}
              </span>
            </div>
            <textarea
              value={context}
              onChange={(e) => setContext(e.target.value)}
              placeholder={text.contextPlaceholder}
              rows={3}
              className="w-full px-5 py-4 text-sm text-slate-800 placeholder:text-slate-400 focus:outline-none resize-none leading-relaxed"
            />
          </div>

          <div className="flex items-center justify-between">
             <div className="flex items-center gap-1.5 text-xs text-slate-400">
              <Info className="w-3.5 h-3.5" />
              {text.hint}
            </div>
            <button
              onClick={handleValidate}
              disabled={!canValidate}
              className="flex items-center gap-2 px-8 py-3 rounded-xl bg-gradient-to-r from-emerald-600 to-teal-600 text-sm font-bold text-white hover:from-emerald-700 hover:to-teal-700 transition-all shadow-lg shadow-emerald-200 disabled:opacity-50 disabled:cursor-not-allowed disabled:shadow-none active:scale-95"
            >
              {loading ? (
                <>
                  <svg className="animate-spin w-4 h-4" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8H4z" />
                  </svg>
                  {text.analyzing}
                </>
              ) : (
                <>
                  <ScanSearch className="w-4 h-4" />
                  {text.validateBtn}
                </>
              )}
            </button>
          </div>
        </div>

        {/* ── Instructions / Rules (Right Column) ─────────────────────────────────── */}
        {!result && !loading && (
          <div className="bg-slate-50 rounded-2xl border border-slate-100 p-5 self-start">
            <h3 className="text-sm font-bold text-slate-800 mb-4 flex items-center gap-2">
              <ShieldCheck className="w-4 h-4 text-emerald-600" />
              {text.criteriaTitle}
            </h3>
            <ul className="space-y-4">
              <li className="flex gap-3">
                <div className="w-6 h-6 rounded-full bg-emerald-100 text-emerald-600 flex items-center justify-center shrink-0">
                  <span className="text-xs font-bold">1</span>
                </div>
                <div>
                  <p className="text-sm font-semibold text-slate-700">{text.c1}</p>
                  <p className="text-xs text-slate-500 mt-0.5">{text.c1d}</p>
                </div>
              </li>
              <li className="flex gap-3">
                <div className="w-6 h-6 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center shrink-0">
                  <span className="text-xs font-bold">2</span>
                </div>
                <div>
                  <p className="text-sm font-semibold text-slate-700">{text.c2}</p>
                  <p className="text-xs text-slate-500 mt-0.5">{text.c2d}</p>
                </div>
              </li>
              <li className="flex gap-3">
                <div className="w-6 h-6 rounded-full bg-purple-100 text-purple-600 flex items-center justify-center shrink-0">
                  <span className="text-xs font-bold">3</span>
                </div>
                <div>
                  <p className="text-sm font-semibold text-slate-700">{text.c3}</p>
                  <p className="text-xs text-slate-500 mt-0.5">{text.c3d}</p>
                </div>
              </li>
            </ul>
          </div>
        )}

        {/* ── Loading Skeleton (Right Column) ───────────────────────────────────── */}
        {loading && (
          <div className="bg-white rounded-2xl border border-slate-100 p-5 space-y-4 animate-pulse self-start">
            <div className="h-4 bg-slate-200 rounded w-1/2 mb-6" />
            <div className="h-24 bg-slate-100 rounded-xl w-full" />
            <div className="h-16 bg-slate-100 rounded-xl w-full" />
            <div className="h-16 bg-slate-100 rounded-xl w-full" />
          </div>
        )}

        {/* ── Validation Results (Right Column) ───────────────────────────────────── */}
        {result && !loading && (
          <div className="space-y-4 self-start">
            
            {/* Score Card */}
            <div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-6 text-center relative overflow-hidden">
               <button onClick={() => setShowSaveModal(true)} className="absolute top-3 right-3 p-1.5 text-violet-600 hover:bg-violet-50 rounded-lg transition z-10" title="Lưu vào Dự án">
                 <FolderPlus className="w-5 h-5" />
               </button>
               <div className="absolute top-0 left-0 w-full h-1.5 bg-gradient-to-r from-emerald-400 to-teal-500" />
               <p className="text-sm font-bold text-slate-500 uppercase tracking-widest mb-2">{text.score}</p>
               <div className="flex items-end justify-center gap-1">
                 <span className={`text-5xl font-black ${result.score >= 80 ? 'text-emerald-600' : result.score >= 50 ? 'text-amber-500' : 'text-red-500'}`}>
                   {result.score}
                 </span>
                 <span className="text-xl font-bold text-slate-400 mb-1">/100</span>
               </div>
               <p className="text-xs text-slate-400 mt-2">
                 {text.scoreDesc}
               </p>
            </div>

            {/* Checklist */}
            <div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-5">
              <h3 className="text-sm font-bold text-slate-800 mb-3">{text.checkTitle}</h3>
              <div className="space-y-2.5">
                {result.formatting.map((item, idx) => (
                  <div key={idx} className="flex items-center justify-between text-sm">
                    <span className="text-slate-600">{item.label}</span>
                    {item.passed ? (
                       <CheckCircle2 className="w-4 h-4 text-emerald-500" />
                    ) : (
                       <AlertTriangle className="w-4 h-4 text-amber-500" />
                    )}
                  </div>
                ))}
              </div>
            </div>

            {/* Suggestions */}
            <div className="bg-violet-50 rounded-2xl border border-violet-100 p-5">
              <h3 className="text-sm font-bold text-violet-800 mb-3 flex items-center gap-2">
                <Search className="w-4 h-4" />
                {text.suggestTitle}
              </h3>
              <ul className="space-y-2">
                {result.suggestions.map((s, i) => (
                  <li key={i} className="flex items-start gap-2 text-xs text-violet-700 leading-relaxed">
                    <ChevronRight className="w-3.5 h-3.5 shrink-0 mt-0.5 opacity-60" />
                    {s}
                  </li>
                ))}
              </ul>
            </div>

          </div>
        )}
      </div>

      {/* ── Hallucination Findings (Bottom Full Width) ─────────────────────────── */}
      {result && !loading && result.hallucinations.length > 0 && (
         <div className="bg-white rounded-2xl border border-red-100 shadow-sm shadow-red-50 p-5">
            <h3 className="text-base font-black text-slate-800 flex items-center gap-2 mb-4">
              <AlertTriangle className="w-5 h-5 text-red-500" />
              {text.dangerTitle}
            </h3>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {result.hallucinations.map((h, i) => (
                <div key={i} className="bg-red-50/50 border border-red-100 rounded-xl p-4">
                  <div className="flex items-center gap-2 mb-2">
                    <span className={`px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider ${
                      h.severity === 'high' ? 'bg-red-200 text-red-700' : 
                      h.severity === 'medium' ? 'bg-amber-200 text-amber-700' : 'bg-slate-200 text-slate-700'
                    }`}>
                      {h.severity} risk
                    </span>
                  </div>
                  <p className="text-sm font-semibold text-slate-800 mb-1.5 line-clamp-2">
                    "{h.text}"
                  </p>
                  <p className="text-xs text-slate-600 leading-relaxed">
                    <span className="font-semibold text-red-600">{text.reasonLabel}</span>
                    {h.reason}
                  </p>
                </div>
              ))}
            </div>
         </div>
      )}

      {/* ── Save Modal ───────────────────────────────────────────────────────── */}
      {result && (
        <SaveToProjectModal
          isOpen={showSaveModal}
          onClose={() => setShowSaveModal(false)}
          data={{
            prompt: output,
            result: result.suggestions.join('\n'),
            aiModel: 'System'
          }}
        />
      )}
    </div>
  );
}
